name: PROD Environment Promotion

on:
  workflow_dispatch:
    inputs:
      Tag:
        description: 'Only uat tag is allowed to prod promotion'
        required: true
        default: 'uat'


env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPO: zurohq-${{ secrets.DOCKER_IMAGE_NAME }}
  PROD_BACKBONE_HOST: ${{ secrets.PROD_BACKBONE_HOST }}
  
jobs:
  deploy:
    name: Deploy tag as PROD docker image
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Configure Docker ECR authentication
        run: aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Tag and Push Docker Image
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPO:uat
          docker tag $ECR_REGISTRY/$ECR_REPO:uat $ECR_REGISTRY/$ECR_REPO:prod
          docker push $ECR_REGISTRY/$ECR_REPO:prod


  compose:
    name: Update docker-compose service with new Docker image
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - name: Connect to the EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ec2-user
          key: ${{ secrets.PROD_KEY }}
          envs: PROD_BACKBONE_HOST
          script: |
            ssh -i zuroprod.pem ec2-user@$PROD_BACKBONE_HOST 'bash -s' < deploy.sh ${{ secrets.DOCKER_IMAGE_NAME }} prod
